"""The sole task interface: uv run inv --list."""

import os
import platform
import re
import shutil
import subprocess
import sys
from pathlib import Path

from flet_cli.utils.android_sdk import AndroidSDK
from invoke.context import Context
from invoke.exceptions import Exit
from invoke.tasks import task
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent
HOSTS = {"linux": "Linux", "windows": "Windows", "macos": "Darwin"}
# Flet otherwise prompts before installing Flutter/Android SDKs, which fails without a TTY.
UNATTENDED = "--yes"


def execute(*args: str, env: dict[str, str] | None = None) -> None:
    sys.stdout.flush()
    try:
        subprocess.run(args, cwd=ROOT, env=os.environ | (env or {}), check=True)
    except FileNotFoundError as exc:
        raise Exit(f"Required command not found: {args[0]}", code=1) from exc
    except subprocess.CalledProcessError as exc:
        raise Exit(
            f"{args[0]} failed with exit code {exc.returncode}", code=exc.returncode
        ) from exc


def require_host(target: str) -> None:
    expected = "Darwin" if target in {"ipa", "ios-simulator", "ios"} else HOSTS.get(target)
    if expected and platform.system() != expected:
        raise Exit(f"{target} requires {expected}; current host is {platform.system()}.", code=1)


def debug_env(debug: bool) -> dict[str, str]:
    return {
        "APP_DEBUG": "1" if debug else "0",
        "PYTHONUNBUFFERED": "1",
        "PYTHONDONTWRITEBYTECODE": "1",
    }


def stage_assets() -> None:
    validate_icon()
    destination = ROOT / "src/assets"
    if destination.is_symlink():
        raise Exit("src/assets must not be a symlink; it is generated by Invoke.", code=1)
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(ROOT / "assets", destination)


def validate_icon() -> None:
    icon = ROOT / "assets/icon.png"
    if not icon.is_file():
        raise Exit("Missing canonical assets/icon.png; see docs/branding.md.", code=1)
    with Image.open(icon) as image:
        if image.format != "PNG" or image.size != (1024, 1024):
            raise Exit("assets/icon.png must be a 1024 x 1024 PNG.", code=1)
        image.verify()


def find_adb() -> str | None:
    if found := shutil.which("adb"):
        return found
    sdk = AndroidSDK.android_home_dir()
    if sdk is None:
        return None
    adb = sdk / "platform-tools" / ("adb.exe" if platform.system() == "Windows" else "adb")
    return str(adb) if adb.is_file() else None


def build_target(target: str, *extra: str) -> None:
    require_host(target)
    (ROOT / "src/app/.debug-mode").unlink(missing_ok=True)
    stage_assets()
    execute("flet", "build", target, UNATTENDED, *extra, env=debug_env(False))


def run_app(*, web: bool = False, debug: bool = False, port: int = 8550) -> None:
    args = [
        "flet",
        "run",
        "src/main.py",
        "--recursive",
        "--assets",
        str(ROOT / "assets"),
        "--ignore-dirs",
        ".flet,__pycache__",
    ]
    if web:
        args += ["--web", "--host", "127.0.0.1", "--port", str(port)]
    if debug:
        args += ["-v"]
    execute(*args, env=debug_env(debug))


@task
def setup(context: Context) -> None:
    """Synchronize the locked development environment."""
    execute("uv", "sync", "--locked")


@task
def run(context: Context) -> None:
    """Desktop hot reload with INFO application logging."""
    run_app()


@task
def run_web(context: Context, port: int = 8550) -> None:
    """Dynamic web hot reload on localhost."""
    run_app(web=True, port=port)


@task
def debug(context: Context) -> None:
    """Desktop hot reload with DEBUG logging and verbose Flet CLI."""
    run_app(debug=True)


@task
def debug_web(context: Context, port: int = 8550) -> None:
    """Dynamic web with DEBUG diagnostics."""
    run_app(web=True, debug=True, port=port)


def debug_mobile(target: str, device: str, list_devices: bool) -> None:
    require_host(target)
    if not device and not list_devices:
        raise Exit("Specify --device=DEVICE_ID or use --list-devices first.", code=1)
    stage_assets()
    args = ["flet", "debug", target, UNATTENDED, "-v", "--no-compile-app"]
    args += ["--device-id", device or "discover"]
    if list_devices:
        args += ["--show-devices"]
    marker = ROOT / "src/app/.debug-mode"
    try:
        marker.write_text("1\n", encoding="ascii")
        execute(*args, env=debug_env(True))
    finally:
        marker.unlink(missing_ok=True)


@task
def debug_android(context: Context, device: str = "", list_devices: bool = False) -> None:
    """Official Android debugging workflow; optional --device or --list-devices."""
    debug_mobile("android", device, list_devices)


@task
def debug_ios(context: Context, device: str = "", list_devices: bool = False) -> None:
    """Official iOS debugging workflow (macOS)."""
    debug_mobile("ios", device, list_devices)


@task
def logs_android(context: Context, device: str = "") -> None:
    """Stream only Flet Python logcat messages; uses PATH or Flet's Android SDK."""
    adb = find_adb()
    if adb is None:
        raise Exit(
            "adb is missing. Run uv run inv build-android once to let Flet install the "
            "Android SDK, or set ANDROID_HOME to an SDK with platform-tools.",
            code=1,
        )
    args = [adb] + (["-s", device] if device else [])
    execute(*args, "logcat", "-s", "flet.python")


@task
def doctor(context: Context) -> None:
    """Report host/tool availability and official Flet diagnostics."""
    print(f"Python: {sys.version.split()[0]} ({sys.executable})")
    print(f"Host: {platform.system()} {platform.machine()}")
    print(f"aws: {shutil.which('aws') or 'not installed (optional)'}")
    print(f"adb: {find_adb() or 'not installed (optional)'}")
    execute("uv", "--version")
    execute("flet", "--version")
    execute("flet", "doctor")


@task
def test(context: Context) -> None:
    """Run all non-GUI regression tests."""
    execute("pytest")


@task
def lint(context: Context) -> None:
    """Run Ruff lint checks."""
    execute("ruff", "check", ".")


@task(name="format")
def format_code(context: Context) -> None:
    """Format Python sources with Ruff."""
    execute("ruff", "format", ".")


@task
def format_check(context: Context) -> None:
    """Check Ruff formatting without modifying files."""
    execute("ruff", "format", "--check", ".")


@task
def typecheck(context: Context) -> None:
    """Run Pyright."""
    execute("pyright")


@task
def check(context: Context) -> None:
    """Run format-check, lint, typecheck, test in order; stop on failure."""
    for operation in (format_check, lint, typecheck, test):
        operation(context)


@task
def clean(context: Context) -> None:
    """Remove generated output and caches, never the uv environment or source assets."""
    (ROOT / "src/app/.debug-mode").unlink(missing_ok=True)
    for relative in ("build", "dist", "src/assets", ".pytest_cache", ".ruff_cache", ".pyright"):
        path = ROOT / relative
        if path.is_symlink():
            path.unlink()
        elif path.exists():
            shutil.rmtree(path)
    for base in (ROOT / "src", ROOT / "tests"):
        for path in base.rglob("__pycache__"):
            shutil.rmtree(path)
    shutil.rmtree(ROOT / "__pycache__", ignore_errors=True)


@task
def build_local(context: Context) -> None:
    """Build the native desktop target for this host."""
    target = next((name for name, host in HOSTS.items() if host == platform.system()), None)
    if target is None:
        raise Exit(f"Unsupported host: {platform.system()}", code=1)
    build_target(target)


def normalize_prefix(prefix: str) -> str:
    prefix = prefix.strip("/")
    if prefix and (
        not re.fullmatch(r"[A-Za-z0-9_./-]+", prefix)
        or any(part in {"", ".", ".."} for part in prefix.split("/"))
    ):
        raise Exit(
            "S3_PREFIX must be a simple relative path without dot or empty segments.", code=1
        )
    return prefix


@task
def build_web(context: Context, base_url: str = "/") -> None:
    """Build static web; --base-url=/prefix/ supports subdirectory hosting."""
    prefix = normalize_prefix(base_url)
    build_target("web", "--base-url", f"/{prefix}/" if prefix else "/")


@task
def serve_web(context: Context, port: int = 8000) -> None:
    """Serve build/web with the official Flet static server."""
    if not (ROOT / "build/web/index.html").is_file():
        raise Exit("No static build. Run uv run inv build-web first.", code=1)
    execute("flet", "serve", "build/web", "--port", str(port))


@task
def deploy_web(context: Context) -> None:
    """Build and sync to S3 with --delete. Destination must contain only this app."""
    prefix = normalize_prefix(os.environ.get("S3_PREFIX", ""))
    build_web(context, base_url=prefix)
    if not shutil.which("aws"):
        raise Exit(
            "AWS CLI is missing. Install AWS CLI v2 and authenticate outside the repo.", code=1
        )
    bucket = os.environ.get("S3_BUCKET", "")
    if not re.fullmatch(r"[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]", bucket):
        raise Exit("Set S3_BUCKET to a bucket name, not an s3:// URL or path.", code=1)
    output = ROOT / "build/web"
    if not (output / "index.html").is_file():
        raise Exit("Build did not produce build/web/index.html.", code=1)
    destination = f"s3://{bucket}/{prefix + '/' if prefix else ''}"
    args = ["aws", "s3", "sync", str(output), destination, "--delete"]
    for variable, option in (("AWS_PROFILE", "--profile"), ("AWS_REGION", "--region")):
        if value := os.environ.get(variable):
            args += [option, value]
    execute(*args)


@task
def build_android(context: Context) -> None:
    """Build Android APK on Linux, Windows, or macOS."""
    build_target("apk")


@task
def build_android_aab(context: Context) -> None:
    """Build Android App Bundle on Linux, Windows, or macOS."""
    build_target("aab")


@task
def build_ios(context: Context) -> None:
    """Build an iOS IPA on macOS; signing must be configured locally."""
    build_target("ipa")


@task
def build_ios_simulator(context: Context) -> None:
    """Build an unsigned iOS Simulator app on macOS."""
    build_target("ios-simulator")


@task
def build_windows(context: Context) -> None:
    """Build Windows desktop on Windows."""
    build_target("windows")


@task
def build_linux(context: Context) -> None:
    """Build Linux desktop on Linux (including a Linux environment in WSL)."""
    build_target("linux")


@task
def build_macos(context: Context) -> None:
    """Build macOS desktop on macOS."""
    build_target("macos")


@task
def icon_placeholder(context: Context) -> None:
    """Create the neutral template icon only if no canonical icon exists."""
    path = ROOT / "assets/icon.png"
    if path.exists():
        raise Exit("assets/icon.png already exists; refusing to overwrite branding.", code=1)
    path.parent.mkdir(parents=True, exist_ok=True)
    image = Image.new("RGBA", (1024, 1024), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    draw.rectangle((0, 0, 1023, 1023), outline="#525252", width=64)
    draw.line((0, 0, 1023, 1023), fill="#a3a3a3", width=100)
    draw.line((1023, 0, 0, 1023), fill="#a3a3a3", width=100)
    image.save(path, format="PNG")


@task
def icon_check(context: Context) -> None:
    """Validate canonical icon format and dimensions."""
    validate_icon()
